# Generated by Django 5.2 on 2025-04-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
